version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "better"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12vzobvle8p4v"
s3_prefix = "better"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
