AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  
  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 250
    Runtime: go1.x

Parameters:
  S3BucketName:
    Type: String
    Description: Name of S3 bucket where swagger spec is stored
  StageName:
    Type: String
    Description: The name of the stage
    Default: dev

Resources:
  CreateGoal:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: bin/goal-create
      Policies: AmazonDynamoDBFullAccess
  
  UpdateGoal:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: bin/goal-edit
      Policies: AmazonDynamoDBFullAccess

  GetGoal:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: bin/goal-get
      Policies: AmazonDynamoDBReadOnlyAccess

  ListGoals:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: bin/goal-list
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        ListGoalEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /goals
            Method: GET
  
  DeleteGoal:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: bin/goal-delete
      Policies: AmazonDynamoDBFullAccess

  RegisterUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: bin/user-signup
      Environment:
        Variables:
          AWS_CLIENT_ID:
          AWS_CLIENT_SECRET:

  VerifyUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: bin/user-verify
      Environment:
        Variables:
          AWS_CLIENT_ID:
          AWS_CLIENT_SECRET:
      
  LoginUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: bin/user-login
      Environment:
        Variables:
          AWS_CLIENT_ID:
          AWS_CLIENT_SECRET:

  LogoutUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: bin/user-logout

  DeleteUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: bin/user-delete

  # API definition
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: better-api-${StageName}
      StageName:
        Ref: StageName
      DefinitionBody:
        Fn::Transform:
          Name: AWS:Include
          Parameters:
            Location:
              Fn::Join:
                - ''
                - - 's3://'
                  - Ref: S3BucketName
                  - '/open-api.yaml'

